bf16: true
cutoff_len: 131072

# check `data/dataset_info.json` for details
dataset: multimodal-mind2web-short # multimodal-mind2web
dataset_dir: data

ddp_timeout: 180000000
do_train: true

# liger kernel
enable_liger_kernel: true

finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
learning_rate: 5.0e-05
logging_steps: 5
lora_alpha: 16
lora_dropout: 0
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 100000
model_name_or_path: Qwen/Qwen2-VL-7B-Instruct

# epochs
num_train_epochs: 3.0

optim: adamw_torch

# output dir
output_dir: output

packing: false

# batch size
per_device_train_batch_size: 1

plot_loss: true
preprocessing_num_workers: 16

# quantization
quantization_bit: 4
quantization_method: bitsandbytes

# wandb, tensorboard
report_to: none

# checkpoint save steps
save_steps: 100

stage: sft
template: qwen2_vl
warmup_steps: 0
